"""Emit the experiment C re-run configs at the cap chosen by tools/calibrate_cap.py.

C asks whether the wall at N=256 is the speculative scorer or `max_num_seqs`, and answers it by
raising the cap so the two explanations predict different concurrencies. The first attempt raised
it to 1024, which backfired: vLLM reserves its profiling activation peak at `max_num_seqs`, so
the cap that was supposed to give the engine *more* room took KV from 4.74 GiB down to 1.63 and
the engine went KV-bound at N ~ 125 — short of the boundary in both arms, in every trial.

The cap therefore cannot be chosen a priori. It has to clear 256 while leaving enough KV to reach
256, and where that window lies is an empirical property of this GPU. The calibration sweep
measures it; this script turns its answer into the two configs.

If no cap qualifies, nothing is written and the driver skips C. That is not a failure: the k=7
arm at the default cap already separates the scorer from the cap, by dying at N ~ 129 where the
cap cannot reach, so C's re-run is corroboration rather than the load-bearing evidence.

Usage:
    python tools/make_regime_configs.py --calibration results/expF/calibration.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_TEMPLATE = """\
# Experiment F-3 (C re-run) — regime dependence, spec decode {state}, cap {cap}.
#
# GENERATED by tools/make_regime_configs.py from {calib}. Do not hand-edit; the cap is a
# measured quantity, not a choice. Regenerate if the calibration is rerun.
#
# The cap is {cap} rather than 1024 because `max_num_seqs` is not free. vLLM sizes its memory
# profiling pass at the cap and reserves the activation peak, leaving KV the remainder:
#
#     cap  256 -> activation 2.52 GiB, KV 4.74 GiB, scorer-bound (dies at N=256, KV ~28%)
#     cap 1024 -> activation 5.64 GiB, KV 1.63 GiB, KV-bound   (survives at N ~ 125, KV ~99%)
#
# The first C attempt used 1024 and so measured the second row, not the question. At {cap} the
# measured KV pool is {kv} GiB, whose estimated KV-bound ceiling is N ~ {est_n} — above the
# scorer boundary at 256, so the engine can reach the boundary before occupancy binds, while the
# cap itself sits above 256 and cannot explain a death there.
#
# Predictions:
#   spec on  — dies near N ~ 256 at ~742 MiB, with the cap unreached and KV occupancy low
#   spec off — no scorer tensor exists, so no OOM; runs to the cap or the KV ceiling
#
# The spec-off arm is the mechanism control. If the engine dies with speculative decoding
# disabled, the failure is not the scorer and the diagnosis is wrong.
model: Qwen/Qwen2.5-3B-Instruct

server:
  base_url: http://localhost:8000
  dtype: float16
  gpu_memory_utilization: 0.9
  max_num_seqs: {cap}
{spec_block}
workload:
  mix:
    short: 0.4
    coding: 0.2
    reasoning: 0.2
    long: 0.2

ramp:
  rates: [2.0, 3.0, 4.0, 5.0, 6.0, 8.0]
  stage_s: 60
  seed: 4242

telemetry:
  interval_s: 0.25
  gpu_index: 0
  cooldown_c: 77

slo:
  ttft_ms: 1000
  tpot_ms: 125
"""

_SPEC_ON = """\
  speculative_config:
    method: ngram
    num_speculative_tokens: 4
    prompt_lookup_min: 2
    prompt_lookup_max: 5
"""

# Absent, not empty: the point of the control arm is that the speculative code path is never
# entered, so the flag is omitted exactly as it is for a plain server.
_SPEC_OFF = ""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--calibration", default="results/expF/calibration.json")
    ap.add_argument("--out-dir", default="configs")
    args = ap.parse_args()

    calib = Path(args.calibration)
    if not calib.exists():
        print(f"[regime-cfg] no calibration at {calib}; skipping C", file=sys.stderr)
        sys.exit(2)

    payload = json.loads(calib.read_text())
    rec = payload.get("recommendation", {})
    cap = rec.get("cap")
    if not cap:
        print(f"[regime-cfg] calibration recommends no cap: {rec.get('note', 'n/a')}",
              file=sys.stderr)
        sys.exit(3)

    written = []
    for state, spec in (("on", _SPEC_ON), ("off", _SPEC_OFF)):
        body = _TEMPLATE.format(
            state=state,
            cap=cap,
            kv=rec.get("kv_gib", "?"),
            est_n=rec.get("est_kv_bound_n", "?"),
            calib=calib,
            spec_block=spec,
        )
        path = Path(args.out_dir) / f"regime_qwen3b_spec_{state}_cap{cap}.yaml"
        path.write_text(body)
        written.append(path)
        print(f"[regime-cfg] wrote {path}")

    # The driver reads this to learn the cap without re-parsing the calibration.
    Path(args.out_dir).joinpath(".regime_cap").write_text(f"{cap}\n")
    print(f"[regime-cfg] cap={cap} ({len(written)} configs)")


if __name__ == "__main__":
    main()
